name: Format Markdown

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Testo da formattare'
        required: true
        type: string
      style:
        description: 'Stile di formattazione'
        required: true
        default: 'social'
        type: choice
        options:
          - social
          - technical
          - blog

jobs:
  format:
    runs-on: ubuntu-latest
    outputs:
      result_path: ${{ steps.save_result.outputs.result_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Format Markdown
        id: format
        run: |
          # Installa dipendenze
          npm install openai
          
          # Crea file con il testo di input
          echo '${{ github.event.inputs.text }}' > input.txt
          
          # Script per formattare
          node -e "
          const OpenAI = require('openai');
          const fs = require('fs');
          
          async function formatText() {
            const text = fs.readFileSync('input.txt', 'utf8');
            const style = '${{ github.event.inputs.style }}';
            
            const endpoint = 'https://models.github.ai/inference/';
            const modelName = 'openai/gpt-4o-mini';
            
            const client = new OpenAI({ 
              baseURL: endpoint, 
              apiKey: '${{ secrets.MY_PERSONAL_TOKEN }}' // Usa il tuo token personale
            });
            
            let systemPrompt = 'You are a helpful assistant specialized in Markdown formatting.';
            if (style === 'social') {
              systemPrompt += ' Format for social media with engaging style.';
            } else if (style === 'technical') {
              systemPrompt += ' Format as technical documentation with proper headers and code blocks.';
            } else {
              systemPrompt += ' Format as a blog post with engaging headings and structure.';
            }
            
            const completion = await client.chat.completions.create({
              messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: 'Transform this text into beautiful, well-formatted Markdown: ' + text }
              ],
              model: modelName
            });
            
            const result = completion.choices[0].message.content;
            fs.writeFileSync('formatted_result.md', result);
            console.log('Formattazione completata!');
          }
          
          formatText().catch(console.error);
          "
      
      - name: Save result to repository
        id: save_result
        run: |
          # Configura git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Crea cartella per i risultati se non esiste
          mkdir -p formatted-results
          
          # Genera nome file con timestamp
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RESULT_FILE="formatted-results/${TIMESTAMP}.md"
          
          # Sposta il file nella cartella
          mv formatted_result.md $RESULT_FILE
          
          # Commit e push
          git add $RESULT_FILE
          git commit -m "Add formatted markdown result [skip ci]"
          git push
          
          # Salva il percorso per step successivi e lo espone come output del job
          echo "result_path=${RESULT_FILE}" >> $GITHUB_OUTPUT
          
      - name: Generate config.js for GitHub Pages
        run: |
          # Crea il file config.js con il token GitHub
          echo "const GITHUB_TOKEN = '${{ secrets.MY_PERSONAL_TOKEN }}';" > ./config.js
          
          # Sposta il file nella directory di distribuzione (se necessario)
          mv ./config.js ./formatted-results/config.js
          
      # Manteniamo anche l'artifact per retrocompatibilità
      - name: Upload result as artifact (legacy)
        uses: actions/upload-artifact@v4
        with:
          name: formatted-markdown
          path: ${{ steps.save_result.outputs.result_path }}