permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Testo da formattare'
        required: true
        type: string
      style:
        description: 'Stile di formattazione'
        required: true
        default: 'social'
        type: choice
        options:
          - social
          - technical
          - blog

jobs:
  format:
    runs-on: ubuntu-latest
    outputs:
      result_path: ${{ steps.save_result.outputs.result_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Format Markdown with curl
        id: format
        env:
          # Usando un token personale per l'autenticazione
          GITHUB_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          # Crea file con il testo di input
          cat > input.txt << 'EOF'
          ${{ github.event.inputs.text }}
          EOF
          
          # Determina il prompt di sistema in base allo stile
          if [ "${{ github.event.inputs.style }}" = "social" ]; then
            SYSTEM_PROMPT="You are a helpful assistant specialized in Markdown formatting. Format for social media with engaging style."
          elif [ "${{ github.event.inputs.style }}" = "technical" ]; then
            SYSTEM_PROMPT="You are a helpful assistant specialized in Markdown formatting. Format as technical documentation with proper headers and code blocks."
          else
            SYSTEM_PROMPT="You are a helpful assistant specialized in Markdown formatting. Format as a blog post with engaging headings and structure."
          fi
          
          # Formatta il prompt utente con il testo da input.txt
          USER_PROMPT="Transform this text into beautiful, well-formatted Markdown: $(cat input.txt)"
          
          echo "Chiamata API GitHub Models con curl..."
          
          # Escape dei caratteri speciali in SYSTEM_PROMPT e USER_PROMPT per JSON
          SYSTEM_PROMPT_ESCAPED=$(echo "$SYSTEM_PROMPT" | sed 's/"/\\"/g')
          USER_PROMPT_ESCAPED=$(echo "$USER_PROMPT" | sed 's/"/\\"/g')
          
          # Usa curl per inviare la richiesta
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_PERSONAL_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"openai/gpt-4o-mini\",
              \"messages\": [
                {
                  \"role\": \"system\",
                  \"content\": \"$SYSTEM_PROMPT_ESCAPED\"
                },
                {
                  \"role\": \"user\",
                  \"content\": \"$USER_PROMPT_ESCAPED\"
                }
              ]
            }" \
            https://models.github.ai/inference > response.json
          
          # Stampa la risposta per debug
          echo "Risposta API:"
          cat response.json
          
          # Estrai il contenuto della risposta
          cat response.json | jq -r '.choices[0].message.content' > formatted_result.md
          
          # Verifica che il risultato sia stato generato correttamente
          if [ ! -s formatted_result.md ]; then
            echo "ERRORE: Risposta API non valida"
            cat response.json
            echo "# Errore di formattazione" > formatted_result.md
            echo "" >> formatted_result.md
            echo "Si è verificato un errore durante la formattazione del testo." >> formatted_result.md
          else
            echo "Formattazione completata con successo!"
          fi
      
      - name: Save result to repository
        id: save_result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p formatted-results
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          RESULT_FILE="formatted-results/${TIMESTAMP}.md"
          mv formatted_result.md $RESULT_FILE
          git add $RESULT_FILE
          git commit -m "Add formatted markdown result [skip ci]"
          git push
          echo "result_path=${RESULT_FILE}" >> $GITHUB_OUTPUT
          
      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: formatted-markdown
          path: ${{ steps.save_result.outputs.result_path }}